version: '3'
services:
  weatherservice:
    build:
      context: .
      dockerfile: WeatherMicroservice/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - zipcodeservice
  zipcodeservice:
    build:
      context: .
      dockerfile: ZipcodeMicroservice/Dockerfile
    ports:
      - "8000:8000"
